

FROM docker:latest



WORKDIR /app
RUN apk add --update --no-cache git openssh-client
COPY builder.sh .

# Windowsin extra merkit pois..
RUN apk add --no-cache dos2unix
RUN dos2unix builder.sh


# chmod 
RUN chmod +x builder.sh

ENTRYPOINT ["/bin/sh","./builder.sh"]








