FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve && \
    addgroup -S nonroot && \
    adduser -S nonroot -G nonroot

USER nonroot

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
